application: watchful-audio-135423
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /wordshuffle
  script: main.app

- url: /transit
  script: main2.app

- url: /.*
  script: main2.app
